config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/new'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get 'pages/index'
  get 'pages/new'
  get '/create', to: 'pages#new'
  post '/create',  to: 'pages#create'
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/profile'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users
  resources :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord

    validates :title, presence: true, length: {maximum: 50 }
    validates :tag, presence: true, length: {maximum: 50 }
    validates :content, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :password_digest, presence: true

  has_secure_password

  # 与えられた文字列のハッシュ値を返す 
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :ensure_logged_in, only: [ :new ]

  def index
    @pages = Page.all
  end

  def new
    @page = Page.new
  end

  def show
    @page = Page.find(params[:id])
  end

  def create
    @page = Page.new(page_params)
    if logged_in?
      if @page.save
        redirect_to @page, flash: {success: "ページは正常に作成されました"}
      else
        render 'new'
      end
    else
      redirect_to root_url, flash: {danger: "管理者以外はページ作成できません"}
    end
  end

  private
    def ensure_logged_in
      if !logged_in?
        redirect_to root_url, flash: {danger: "管理者以外はページ作成できません"}
      end
    end

    def page_params
      params.require(:page).permit(:title, :tag, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'メールアドレスまたはパスワードに誤りがあります'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url, flash: {success: 'ログアウトしました'}
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if false
      if @user.save
        redirect_to @user
      else
        render 'new'
      end
    else
      flash.now[:danger] = "現在新規ユーザーは作成できません"
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :password,
        :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/index.html.erb
<% provide(:title, 'Page Index') %>
<h1>記事一覧</h1>

<div class="col-md-6 col-md-offset-3">
    <% @pages.each do |page| %>
        <%= link_to "#{page.title}", page %>
    <% end %>
</div>

<div class = "footer">
    <%= link_to "トップページ", root_path %>
</div>

app/views/pages/new.html.erb
<% provide(:title, 'Create Page') %>
<%= flash[:danger] %>
<h1>Create Page</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@page, url: create_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label "タイトル" %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label "タグ" %>
      <%= f.select :tag, ["プログラミング関連", "競プロ関連", "その他"],
       class: 'form-control' %>

      <%= f.label "内容" %>
      <%= f.text_area :content, class: 'form-control' %>

      <%= f.submit "Create page", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/pages/show.html.erb
<% provide(:title, "#{@page.title}") %>
<h1><%= @page.title %></h1>

<div class = "category-display">
    <h5><%= @page.tag %></h5>
</div>

<div class = "body">
    <%= @page.content %>
</div>

<div class = "footer">
    <%= link_to "記事一覧に戻る", pages_index_path %>
    <%= link_to "トップページ", root_path %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user&.errors&.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if @page&.errors&.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@page.errors.count, "error") %>.
    </div>
    <ul>
    <% @page.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<%= flash[:success] %>
<%= flash[:danger] %>
<h1>Carmine's Page!</h1>
<h2>
  カーミンのページ
</h2>

<div class = "body">
  <h3>
    <%= link_to "プロフィール", static_pages_profile_path %>
  </h3>

  <h3>
    <%= link_to "記事一覧", pages_index_path %>
  </h3>
</div>

app/views/static_pages/profile.html.erb
<% provide(:title, "プロフィール") %>
<h1>プロフィール</h1>

<div class = "footer">
    <%= link_to "トップページ", root_path %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'User Index') %>
<h1>ユーザー一覧</h1>

<div class="col-md-6 col-md-offset-3">
    <% @users.each do |user| %>
        <%= link_to "#{user.name}", user %>
    <% end %>
</div>

<div class = "footer">
    <%= link_to "トップページ", root_path %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'ユーザー登録') %>
<%= flash[:danger] %>
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "#{@user.name}") %>
<%= flash[:success] %>
<h1><%= @user.name %></h1>
<%= link_to "記事投稿", pages_new_path %>
<%= link_to "ログアウト", logout_path %>

<div class = "footer">
    <%= link_to "ユーザー一覧に戻る", users_index_path %>
    <%= link_to "トップページ", root_path %>
</div>